### ISSUE TITLE
Formula seems to be unreadable?

### ISSUE THREAD

**Issue by jjank** [AtomicJar/homebrew-tap#17]
Hi there 😄 

I was just trying to upgrade my `testcontainers-cloud-desktop` but ran into a problem with the formula:

```sh
$ brew update && brew upgrade testcontainers-cloud-desktop

Error: Cask 'testcontainers-cloud-desktop' is unreadable: /usr/local/Homebrew/Library/Taps/atomicjar/homebrew-tap/Casks/testcontainers-cloud-desktop.rb:34: syntax error, unexpected tSTRING_BEG, expecting ']'
        "~/Library/Application Support...
        ^
/usr/local/Homebrew/Library/Taps/atomicjar/homebrew-tap/Casks/testcontainers-cloud-desktop.rb:34: syntax error, unexpected ',', expecting end
.../testcontainers.cloud.desktop",
...                              ^
/usr/local/Homebrew/Library/Taps/atomicjar/homebrew-tap/Casks/testcontainers-cloud-desktop.rb:35: syntax error, unexpected ',', expecting end-of-input
...    "~/Library/Logs/AtomicJar",
...                              ^
``` 

Is this something I can resolve with `brew` myself or does the formula actually have an error?

If it's any help here is the output of `brew -v`:
```
Homebrew 4.0.28-35-g18b4fc4
Homebrew/homebrew-core (git revision 73e3f97befb; last commit 2023-07-11)
Homebrew/homebrew-cask (git revision 11631b8517; last commit 2023-07-11)
```

Thanks four your help!

**Comment by ekcasey** [comment]
Hey @jjank! Thanks for the bug report and apologies for the slow reply. We recently [fixed](https://github.com/AtomicJar/homebrew-tap/commit/aa87fa721c51f3f33654402e27251270a67367df) an error with the tap. I am guess this caused the issue you saw. Please let us know if you are still running into issues!

**Comment by jjank** [comment]
Yes that indeed fixed the issue - many thanks 👍
